backend:
  name: git-gateway
  branch: master
media_folder: img
public_folder: img
publish_mode: editorial_workflow
locale: 'pt'
slug:
  encoding: 'ascii'
  clean_accents: true
#site_url: https://your-site.com
collections:
  - label: 'Páginas'
    name: 'pages'
    folder: 'pages'
    create: true
    extension: 'md'
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Texto na navegação', name: 'navigation', widget: 'string' }
      - {
          label: 'URL (Colocar entre barras, por exemplo: /psicologia/)',
          name: 'permalink',
          widget: 'string'
        }
      - { label: 'Meta Description', name: 'meta_description', widget: 'text' }
      - { label: 'Página', name: 'body', widget: 'markdown' }
  - label: 'Páginas SEO'
    name: 'seo'
    folder: 's'
    create: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - {
          label: 'URL (Colocar entre barras, por exemplo: /psicologia/)',
          name: 'permalink',
          widget: 'string'
        }
      - { label: 'Meta Description', name: 'meta_description', widget: 'text' }
      - { label: 'Texto', name: 'body', widget: 'markdown' }
  - label: 'Artigos'
    name: 'posts'
    folder: 'posts'
    create: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Data', name: 'date', widget: 'datetime' }
      - { label: 'Texto', name: 'body', widget: 'markdown' }
