backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
