backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - label: 'Páginas'
    name: 'pages'
    folder: 'content/pages'
    create: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Link na navegação', name: 'navigation', widget: 'string' }
      - { label: 'Página', name: 'body', widget: 'markdown' }
  - label: 'Artigos'
    name: 'posts'
    folder: 'content/posts'
    create: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Data', name: 'date', widget: 'datetime' }
      - { label: 'Texto', name: 'body', widget: 'markdown' }
